# Generated by Django 4.1.7 on 2023-03-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='budget',
            field=models.IntegerField(help_text='Escribe el presupuesto usado en esta pelicula.', null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='profits',
            field=models.IntegerField(help_text='Escribe las ganancias de esta pelicula.', null=True),
        ),
    ]
