# Generated by Django 4.1.7 on 2023-03-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_movies_budget_alter_movies_profits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
