# Generated by Django 4.1.7 on 2023-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_actors_actor_rename_directors_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('R', 'Retired'), ('D', 'Died')], default='A', help_text='Determinar el estado de actividad del actor.', max_length=1),
        ),
        migrations.AlterField(
            model_name='director',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('R', 'Retired'), ('D', 'Died')], default='A', help_text='Determinar el estado de actividad del director.', max_length=1),
        ),
    ]
