# Generated by Django 4.1.7 on 2023-03-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_actor_status_alter_director_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('R', 'Retired'), ('D', 'Died')], default='A', help_text='Determinar el estado de actividad del actor.', max_length=8),
        ),
        migrations.AlterField(
            model_name='director',
            name='date_of_death',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
