# Generated by Django 4.1.7 on 2023-03-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_actor_movies_remove_director_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=100000000, help_text='Escribe el presupuesto usado en esta pelicula.', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='profits',
            field=models.IntegerField(default=300000000, help_text='Escribe las ganancias de esta pelicula.', null=True),
        ),
    ]
